import os
from datetime import datetime
import sib_api_v3_sdk
from sib_api_v3_sdk.rest import ApiException
from .chart_service import generate_trend_chart_url

def get_brevo_client():
    """
    Obtain the Brevo API client. For now, it returns None to indicate mock mode unless key is present.
    """
    api_key = os.getenv("BREVO_API_KEY")
    if not api_key:
        return None
        
    configuration = sib_api_v3_sdk.Configuration()
    configuration.api_key['api-key'] = api_key
    return sib_api_v3_sdk.TransactionalEmailsApi(sib_api_v3_sdk.ApiClient(configuration))

def generate_html_email(kpis: list, narrative_text: str, chart_url: str) -> str:
    """
    Generates a visually appealing HTML email template.
    """
    kpi_html = ""
    for k in kpis:
        trend_color = "green" if k['dod_pct'] > 0 else "red" if k['dod_pct'] < 0 else "gray"
        kpi_html += f"""
        <div style="border: 1px solid #e5e7eb; padding: 15px; border-radius: 8px; margin-bottom: 10px; background-color: #f9fafb;">
            <h3 style="margin: 0; color: #374151; font-family: Helvetica, Arial, sans-serif;">{k['kpi_name']}</h3>
            <p style="font-size: 24px; font-weight: bold; margin: 5px 0; color: #111827;">{k['value']:,.2f}</p>
            <p style="margin: 0; color: {trend_color}; font-weight: bold;">{k['dod_pct']:+.1f}% vs yesterday</p>
        </div>
        """
        
    return f"""
    <div style="font-family: Helvetica, Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h1 style="color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px;">Daily Analytics Briefing</h1>
        
        <h2>Executive Summary</h2>
        <p style="font-size: 16px; line-height: 1.5; color: #4b5563;">{narrative_text}</p>
        
        <h2>Performance Trend</h2>
        <img src="{chart_url}" alt="KPI Trend Chart" style="width: 100%; height: auto; border: 1px solid #e5e7eb; border-radius: 8px;" />
        
        <h2>Current Metrics</h2>
        {kpi_html}
        
        <p style="font-size: 12px; color: #9ca3af; margin-top: 30px; text-align: center;">Automatically generated by the SAAS-PWA System</p>
    </div>
    """

def send_automated_briefing(to_email: str, kpis: list, anomalies: list, narrative_text: str, historical_df):
    """
    Constructs the charts and templates and dispatches the briefing.
    """
    chart_url = generate_trend_chart_url(historical_df)
    html_content = generate_html_email(kpis, narrative_text, chart_url)

    client = get_brevo_client()
    
    # Mock behavior if client is missing
    if not client:
        print(f"[{datetime.now().isoformat()}] INFO: Brevo API Key missing. Simulation mode for {to_email}")
        return {"status": "success", "mock": True, "chart_url": chart_url}

    # Live Brevo sending logic
    send_smtp_email = sib_api_v3_sdk.SendSmtpEmail(
        to=[{"email": to_email}],
        sender={"name": "SAAS-PWA System", "email": "reports@saas-pwa.local"},
        subject="Your Daily Analytics Briefing",
        html_content=html_content
    )
    
    try:
        api_response = client.send_transac_email(send_smtp_email)
        return {"status": "success", "message_id": api_response.message_id}
    except ApiException as e:
        print(f"Exception when calling SMTPApi->send_transac_email: {e}")
        return {"status": "error", "message": str(e)}

def send_anomaly_alert(to_email: str, anomaly_data: dict):
    # Implementation stub for standalone alerts
    pass
