import os
import httpx
import logging
from datetime import datetime, date
from groq import Groq

logger = logging.getLogger(__name__)

BASE_DEFINITIONS = """
STANDARD METRIC DEFINITIONS:
- Net Revenue = Gross Revenue minus Returns and Discounts
- Customer Count = Number of unique active accounts in the reporting period
- Gross Margin = (Revenue minus COGS) divided by Revenue, expressed as a percentage
- Inventory Value = Total current valuation of stock on hand
- Support Tickets = Count of customer support requests (open or resolved)
- DoD % = Day-over-Day percentage change
- WoW % = Week-over-Week percentage change
"""


def _rag_status(kpis: list) -> str:
    """Return RED / AMBER / GREEN based on KPI statuses."""
    statuses = [k.get("status", "NORMAL") for k in kpis]
    if any(s == "CRITICAL" for s in statuses):
        return "RED"
    if any(s == "WARNING" for s in statuses):
        return "AMBER"
    return "GREEN"


def _kpi_table_text(kpis: list) -> str:
    lines = []
    for k in kpis:
        name = k.get("kpi_name", "").replace("_", " ").title()
        val = f"{k.get('value', 0):,.2f}"
        dod = f"{k.get('dod_pct', 0):+.1f}%" if k.get("dod_pct") is not None else "N/A"
        wow = f"{k.get('wow_pct', 0):+.1f}%" if k.get("wow_pct") is not None else "N/A"
        status = k.get("status", "NORMAL")
        lines.append(f"  - {name}: {val} | DoD: {dod} | WoW: {wow} | Status: {status}")
    return "\n".join(lines) if lines else "  No KPI data available."


def _anomaly_text(anomalies: list) -> str:
    if not anomalies:
        return "  No anomalies detected in this period."
    lines = []
    for a in anomalies:
        name = a.get("kpi_name", "").replace("_", " ").title()
        sev = a.get("severity", "WARNING")
        reason = a.get("context", {}).get("reason", "Deviation detected")
        dev = a.get("deviation", 0)
        lines.append(f"  [{sev}] {name}: {reason} (z-score deviation: {dev:.1f})")
    return "\n".join(lines)


def build_structured_report_prompt(
    kpis: list,
    anomalies: list,
    tone: str,
    instruction: str,
    company_name: str,
    report_period: str,
    report_type: str,
    base_definitions: str,
    custom_format: dict = None,
) -> str:
    rag = _rag_status(kpis)
    kpi_table = _kpi_table_text(kpis)
    anomaly_text = _anomaly_text(anomalies)
    today = date.today().strftime("%B %d, %Y")
    defs = base_definitions or BASE_DEFINITIONS
    focus = f"\nSTRATEGIC FOCUS: {instruction}" if instruction else ""

    if custom_format:
        # User-defined report structure
        sections = "\n".join(
            f"- {s.get('title', '')}: {s.get('description', '')}"
            for s in custom_format.get("sections", [])
        )
        format_instruction = f"""
The manager has requested a CUSTOM report structure. Follow it exactly:
{sections}

Additional notes from manager: {custom_format.get('notes', 'None')}
"""
    else:
        format_instruction = f"""
Generate a PROFESSIONAL STRUCTURED REPORT with ALL of the following sections in order:

1. HEADER
   Report Title: {report_type} Performance Report — {report_period}
   Period Covered: {report_period}
   Prepared For: {company_name} Management
   Date Submitted: {today}

2. EXECUTIVE SUMMARY
   - Overall System Status: {rag} (RAG indicator)
   - Write 3–5 bullet points covering the most critical findings
   - State the top 1–2 recommended actions

3. KEY PERFORMANCE INDICATORS
   Use this data:
{kpi_table}
   - Describe trends, compare to previous period where possible
   - Highlight any KPI that is above or below target

4. ANOMALIES & ALERTS
{anomaly_text}
   - Explain the business implication of each anomaly
   - Suggest investigation steps

5. UPCOMING PRIORITIES
   - Based on the data, list 2–3 recommended priorities for the next reporting period
   - Identify any risk areas that need monitoring

6. APPENDIX NOTE
   - Mention that full raw data and charts are available in the SAAS dashboard
   - Include a note that this report was auto-generated by the SAAS analytics system
"""

    tone_instruction = (
        "Use formal, precise business language. No casual phrasing."
        if tone == "formal"
        else "Use clear, direct, insight-driven language. Be specific about numbers and implications."
    )

    return f"""You are a senior business analyst writing a {report_type.lower()} performance report for {company_name}.

{defs}
{focus}

DATA PROVIDED:
KPIs:
{kpi_table}

ANOMALIES:
{anomaly_text}

{format_instruction}

TONE: {tone_instruction}
IMPORTANT: Write the complete report. Use the actual numbers from the data. Do not use placeholders. Keep it under 600 words total."""


def generate_live_narrative(
    kpi_data: list,
    anomaly_data: list,
    tone: str = "insight-driven",
    instruction: str = None,
    base_definitions: str = None,
    prompt_template: str = None,
    company_name: str = "your company",
    report_period: str = None,
    report_type: str = "Daily",
    custom_format: dict = None,
):
    """
    Generate a structured professional report narrative.
    Uses Groq (primary) → Ollama (fallback) → template (final fallback).
    """
    if not report_period:
        report_period = date.today().strftime("%B %d, %Y")

    groq_api_key = os.getenv("GROQ_API_KEY")

    if prompt_template:
        # Legacy custom prompt template path
        prompt = prompt_template.format(
            company_name=company_name,
            user_tone=tone,
            user_instruction=instruction or "Provide the most important operational insights.",
            kpis=kpi_data,
            anomalies=anomaly_data,
            definitions=base_definitions or BASE_DEFINITIONS,
        )
    else:
        prompt = build_structured_report_prompt(
            kpis=kpi_data,
            anomalies=anomaly_data,
            tone=tone,
            instruction=instruction,
            company_name=company_name,
            report_period=report_period,
            report_type=report_type,
            base_definitions=base_definitions or BASE_DEFINITIONS,
            custom_format=custom_format,
        )

    # 1. Groq (primary)
    if groq_api_key:
        try:
            client = Groq(api_key=groq_api_key)
            completion = client.chat.completions.create(
                model="llama3-70b-8192",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.6,
                max_tokens=900,
            )
            return completion.choices[0].message.content
        except Exception as e:
            logger.error(f"Groq API Error: {e}")

    # 2. Ollama (fallback)
    try:
        response = httpx.post(
            "http://localhost:11434/api/generate",
            json={"model": "llama3", "prompt": prompt, "stream": False},
            timeout=15.0,
        )
        if response.status_code == 200:
            return response.json().get("response")
    except Exception as e:
        logger.warning(f"Ollama Fallback Failed: {e}")

    # 3. Template fallback
    return _build_fallback_report(kpi_data, anomaly_data, company_name, report_period, report_type)


def _build_fallback_report(kpis, anomalies, company_name, report_period, report_type) -> str:
    rag = _rag_status(kpis)
    today = date.today().strftime("%B %d, %Y")
    kpi_lines = []
    for k in kpis:
        name = k.get("kpi_name", "").replace("_", " ").title()
        val = k.get("value", 0)
        dod = k.get("dod_pct", 0) or 0
        trend = "increased" if dod > 0 else "decreased"
        kpi_lines.append(f"{name} is {val:,.2f}, {trend} {abs(dod):.1f}% day-over-day.")

    anomaly_lines = []
    for a in anomalies:
        name = a.get("kpi_name", "").replace("_", " ").title()
        sev = a.get("severity", "WARNING")
        reason = a.get("context", {}).get("reason", "Deviation detected")
        anomaly_lines.append(f"[{sev}] {name}: {reason}")

    return f"""{report_type} Performance Report — {report_period}
Prepared For: {company_name} Management | Date: {today}

EXECUTIVE SUMMARY
Overall Status: {rag}
{"  ".join(kpi_lines[:3]) or "No KPI data available for this period."}
{"Anomalies detected: " + str(len(anomalies)) + " issue(s) require attention." if anomalies else "No anomalies detected."}

KEY PERFORMANCE INDICATORS
{chr(10).join(kpi_lines) or "No KPI data available."}

ANOMALIES & ALERTS
{chr(10).join(anomaly_lines) or "No anomalies detected in this period."}

UPCOMING PRIORITIES
Review flagged KPIs and investigate any anomalies before the next reporting cycle.
Ensure data connections remain active for continuous monitoring.

APPENDIX
Full raw data, charts, and historical trends are available in the SAAS dashboard.
This report was auto-generated by the SAAS Analytics System."""
