import os
import httpx
import logging
from datetime import datetime, date
from .groq_utils import execute_groq_completion, get_groq_model

logger = logging.getLogger(__name__)

BASE_DEFINITIONS = """
STANDARD METRIC DEFINITIONS:
- Value: The measured quantity for this KPI in the reporting period
- DoD %: Day-over-Day percentage change from the previous day
- WoW %: Week-over-Week percentage change from the same day last week
- Status NORMAL: Value is within expected range
- Status WARNING: Value shows a notable deviation (z-score > 1.5)
- Status CRITICAL: Value shows a significant anomaly (z-score > 2.5)
"""


def _rag_status(kpis: list) -> str:
    """Return RED / AMBER / GREEN based on KPI statuses."""
    statuses = [k.get("status", "NORMAL") for k in kpis]
    if any(s == "CRITICAL" for s in statuses):
        return "RED"
    if any(s == "WARNING" for s in statuses):
        return "AMBER"
    return "GREEN"


def _kpi_table_text(kpis: list) -> str:
    lines = []
    for k in kpis:
        name = k.get("kpi_name", "").replace("_", " ").title()
        val = f"{k.get('value', 0):,.2f}"
        dod = f"{k.get('dod_pct', 0):+.1f}%" if k.get("dod_pct") is not None else "N/A"
        wow = f"{k.get('wow_pct', 0):+.1f}%" if k.get("wow_pct") is not None else "N/A"
        status = k.get("status", "NORMAL")
        lines.append(f"  - {name}: {val} | DoD: {dod} | WoW: {wow} | Status: {status}")
    return "\n".join(lines) if lines else "  No KPI data available."


def _anomaly_text(anomalies: list) -> str:
    if not anomalies:
        return "  No anomalies detected in this period."
    lines = []
    for a in anomalies:
        name = a.get("kpi_name", "").replace("_", " ").title()
        sev = a.get("severity", "WARNING")
        reason = a.get("context", {}).get("reason", "Deviation detected")
        dev = a.get("deviation", 0)
        lines.append(f"  [{sev}] {name}: {reason} (z-score deviation: {dev:.1f})")
    return "\n".join(lines)


def build_structured_report_prompt(
    kpis: list,
    anomalies: list,
    tone: str,
    instruction: str,
    company_name: str,
    report_period: str,
    report_type: str,
    base_definitions: str,
    custom_format: dict = None,
) -> str:
    rag = _rag_status(kpis)
    kpi_table = _kpi_table_text(kpis)
    anomaly_text = _anomaly_text(anomalies)
    today = date.today().strftime("%B %d, %Y")
    defs = base_definitions or BASE_DEFINITIONS
    focus = f"\nSTRATEGIC FOCUS: {instruction}" if instruction else ""

    if custom_format:
        # User-defined report structure
        sections = "\n".join(
            f"- {s.get('title', '')}: {s.get('description', '')}"
            for s in custom_format.get("sections", [])
        )
        format_instruction = f"""
The manager has requested a CUSTOM report structure. Follow it exactly:
{sections}

Additional notes from manager: {custom_format.get('notes', 'None')}
"""
    else:
        format_instruction = f"""
Generate a PROFESSIONAL STRUCTURED REPORT with ALL of the following sections in order:

1. HEADER
   Report Title: {report_type} Performance Report — {report_period}
   Period Covered: {report_period}
   Prepared For: {company_name} Management
   Date Submitted: {today}

2. EXECUTIVE SUMMARY
   - Overall System Status: {rag} (RAG indicator)
   - Write 3–5 bullet points covering the most critical findings
   - State the top 1–2 recommended actions

3. KEY PERFORMANCE INDICATORS
   Use this data:
{kpi_table}
   - Describe trends, compare to previous period where possible
   - Highlight any KPI that is above or below target

4. ANOMALIES & ALERTS
{anomaly_text}
   - Explain the business implication of each anomaly
   - Suggest investigation steps

5. UPCOMING PRIORITIES
   - Based on the data, list 2–3 recommended priorities for the next reporting period
   - Identify any risk areas that need monitoring

6. APPENDIX NOTE
   - Mention that full raw data and charts are available in the SAAS dashboard
   - Include a note that this report was auto-generated by the SAAS analytics system
"""

    tone_instruction = (
        "Use formal, precise business language. No casual phrasing."
        if tone == "formal"
        else "Use clear, direct, insight-driven language. Be specific about numbers and implications."
    )

    return f"""You are a senior business analyst writing a {report_type.lower()} performance report for {company_name}.

{defs}
{focus}

DATA PROVIDED:
KPIs:
{kpi_table}

ANOMALIES:
{anomaly_text}

{format_instruction}

TONE: {tone_instruction}
CRITICAL RULES:
- Only use the KPI data and anomaly data provided above. Do NOT reference any external database, RNA sequences, SQL tables, or any data source not listed here.
- Do NOT suggest SQL queries or describe database schemas.
- Do NOT invent KPI names, values, or metrics not present in the data above.
- If the data is empty or minimal, say so clearly and recommend running a sync.
IMPORTANT: Write the complete report. Use the actual numbers from the data. Do not use placeholders. Keep it under 600 words total."""


def generate_live_narrative(
    kpi_data: list,
    anomaly_data: list,
    tone: str = "insight-driven",
    instruction: str = None,
    base_definitions: str = None,
    prompt_template: str = None,
    company_name: str = "your company",
    report_period: str = None,
    report_type: str = "Daily",
    custom_format: dict = None,
):
    """
    Generate a structured professional report narrative.
    Uses Groq (primary) → Ollama (fallback) → template (final fallback).
    """
    if not report_period:
        report_period = date.today().strftime("%B %d, %Y")

    groq_api_key = os.getenv("GROQ_API_KEY")

    if prompt_template:
        # Legacy custom prompt template path
        prompt = prompt_template.format(
            company_name=company_name,
            user_tone=tone,
            user_instruction=instruction or "Provide the most important operational insights.",
            kpis=kpi_data,
            anomalies=anomaly_data,
            definitions=base_definitions or BASE_DEFINITIONS,
        )
    else:
        prompt = build_structured_report_prompt(
            kpis=kpi_data,
            anomalies=anomaly_data,
            tone=tone,
            instruction=instruction,
            company_name=company_name,
            report_period=report_period,
            report_type=report_type,
            base_definitions=base_definitions or BASE_DEFINITIONS,
            custom_format=custom_format,
        )

    # 1. Groq (primary)
    if groq_api_key:
        try:
            completion = execute_groq_completion(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.6,
                max_tokens=900,
                model=get_groq_model(),
            )
            return completion.choices[0].message.content
        except Exception as e:
            logger.error(f"Groq API Error: {e}")

    # 2. Ollama (fallback)
    try:
        response = httpx.post(
            "http://localhost:11434/api/generate",
            json={"model": "llama3", "prompt": prompt, "stream": False},
            timeout=15.0,
        )
        if response.status_code == 200:
            return response.json().get("response")
    except Exception as e:
        logger.warning(f"Ollama Fallback Failed: {e}")

    # 3. Template fallback
    return _build_fallback_report(kpi_data, anomaly_data, company_name, report_period, report_type)


def _build_fallback_report(kpis, anomalies, company_name, report_period, report_type) -> str:
    rag = _rag_status(kpis)
    today = date.today().strftime("%B %d, %Y")
    kpi_lines = []
    for k in kpis:
        name = k.get("kpi_name", "").replace("_", " ").title()
        val = k.get("value", 0)
        dod = k.get("dod_pct", 0) or 0
        trend = "increased" if dod > 0 else "decreased"
        kpi_lines.append(f"{name} is {val:,.2f}, {trend} {abs(dod):.1f}% day-over-day.")

    anomaly_lines = []
    for a in anomalies:
        name = a.get("kpi_name", "").replace("_", " ").title()
        sev = a.get("severity", "WARNING")
        reason = a.get("context", {}).get("reason", "Deviation detected")
        anomaly_lines.append(f"[{sev}] {name}: {reason}")

    return f"""{report_type} Performance Report — {report_period}
Prepared For: {company_name} Management | Date: {today}

EXECUTIVE SUMMARY
Overall Status: {rag}
{"  ".join(kpi_lines[:3]) or "No KPI data available for this period."}
{"Anomalies detected: " + str(len(anomalies)) + " issue(s) require attention." if anomalies else "No anomalies detected."}

KEY PERFORMANCE INDICATORS
{chr(10).join(kpi_lines) or "No KPI data available."}

ANOMALIES & ALERTS
{chr(10).join(anomaly_lines) or "No anomalies detected in this period."}

UPCOMING PRIORITIES
Review flagged KPIs and investigate any anomalies before the next reporting cycle.
Ensure data connections remain active for continuous monitoring.

APPENDIX
Full raw data, charts, and historical trends are available in the SAAS dashboard.
This report was auto-generated by the SAAS Analytics System."""


def generate_database_overview_narrative(
    schema: dict,
    tone: str = "insight-driven",
    instruction: str = None,
    company_name: str = "your company",
) -> str:
    """Generate a clean, structured database overview narrative using LLM,
    focusing on what the database is about rather than listing tables.
    """
    tables = schema.get("tables", [])
    dialect = schema.get("dialect", "unknown")
    
    # Create a compact schema summary for the LLM prompt without raw table lists for output
    schema_details = []
    for tbl in tables[:15]:
        tbl_name = tbl.get("qualified_name") or tbl.get("name")
        cols = [c.get("name") for c in tbl.get("columns", [])[:10]]
        schema_details.append(f"- Table: {tbl_name} | Columns: {', '.join(cols)}")
    schema_summary_text = "\n".join(schema_details)

    focus = f"\nUSER ANALYSIS INSTRUCTION / STRATEGIC FOCUS:\n{instruction}" if instruction else ""

    prompt = f"""You are a senior data analyst and business intelligence expert.
You have been connected to a client database of type: {dialect}.
Here is a summary of the database schema (tables and columns):
{schema_summary_text}

Write a CLEAR, STRUCTURED, and SIMPLE narrative explaining what this database is about in a professional business context.
{focus}

CRITICAL RULES:
1. Do NOT list the tables one by one with bullet points showing their columns or row counts. The user already sees the schema list elsewhere.
2. Just explain in 2-3 structured paragraphs what the database represents operational-wise (e.g. customer success, billing, user engagement, inventory tracking, etc.), what core workflows it maps, and what kinds of insights can be derived from it.
3. If a USER ANALYSIS INSTRUCTION is provided above, incorporate it fully to add more context and tailor the explanation to that focus.
4. Do NOT say "The system did not find configured KPI mappings" or mention that anything is missing or failed.
5. Keep it straight, forward, simple, and professional. Write the complete narrative. No placeholders. Max 350 words.
"""

    # 1. Groq (primary)
    groq_api_key = os.getenv("GROQ_API_KEY")
    if groq_api_key:
        try:
            completion = execute_groq_completion(
                messages=[{"role": "user", "content": prompt}],
                temperature=0.5,
                max_tokens=600,
                model=get_groq_model(),
            )
            return completion.choices[0].message.content
        except Exception as e:
            logger.error(f"Groq API Error in overview narrative: {e}")

    # 2. Ollama (fallback)
    try:
        response = httpx.post(
            "http://localhost:11434/api/generate",
            json={"model": "llama3", "prompt": prompt, "stream": False},
            timeout=15.0,
        )
        if response.status_code == 200:
            return response.json().get("response")
    except Exception as e:
        logger.warning(f"Ollama Overview Fallback Failed: {e}")

    # 3. Fallback narrative template (if LLMs fail or are offline)
    table_names = [t.get("name", "").lower() for t in tables]
    
    is_nps = any("nps" in n or "feedback" in n or "score" in n for n in table_names)
    is_sales = any("sales" in n or "order" in n or "invoice" in n or "transaction" in n for n in table_names)
    is_users = any("user" in n or "customer" in n or "member" in n for n in table_names)

    summary = f"This connected {dialect} database for {company_name} serves as a central operational data store. "
    
    topics = []
    if is_nps:
        topics.append("customer feedback and Net Promoter Scores (NPS) to track user satisfaction")
    if is_sales:
        topics.append("transaction records and financial orders to monitor business revenue")
    if is_users:
        topics.append("user profiles and account segmentations to understand demographics")
    
    if topics:
        summary += "Based on our structural analysis, it primarily manages " + " and ".join(topics) + "."
    else:
        summary += f"It contains {len(tables)} tables tracking operational logs and data assets."

    summary += "\n\n"
    if instruction:
        summary += f"Under the strategic directive: '{instruction}', we are analyzing relationships across these data entities to surface optimizations. "
    
    summary += "You can use the Schema Explorer to map specific fields to standard KPIs, or use the Ask Your Data interface to write natural language queries and retrieve precise insights directly from this schema."
    
    return summary
