-- Migration 003: New tables for forecasting, audit log
-- Run this in your Supabase SQL editor

-- 7-day KPI forecasts generated by Prophet
CREATE TABLE IF NOT EXISTS kpi_forecasts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    department_id UUID REFERENCES departments(id) ON DELETE SET NULL,
    kpi_name TEXT NOT NULL,
    forecast_date DATE NOT NULL,
    predicted_value NUMERIC NOT NULL,
    lower_bound NUMERIC NOT NULL,
    upper_bound NUMERIC NOT NULL,
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_kpi_forecasts_user ON kpi_forecasts(user_id);
CREATE INDEX IF NOT EXISTS idx_kpi_forecasts_date ON kpi_forecasts(forecast_date);

ALTER TABLE kpi_forecasts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own forecasts" ON kpi_forecasts
    FOR ALL USING (auth.uid() = user_id);

-- Configuration change audit log
CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    action TEXT NOT NULL,       -- 'create', 'update', 'delete'
    entity TEXT NOT NULL,       -- 'preferences', 'connection', 'mapping', 'role', 'department'
    changes JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC);

ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users see own audit logs" ON audit_logs
    FOR ALL USING (auth.uid() = user_id);
