-- ======================================================================
-- CNPS Realistic Demo for Oracle 19c
-- Run in SQL*Plus or Oracle SQL Developer
-- Creates CNPS-style tables with realistic anomalies and test data
-- ======================================================================
-- Usage:
--   sqlplus system/your_password@XEPDB1 @scripts/oracle_cnps_demo.sql
-- ======================================================================

SET SERVEROUTPUT ON;
SET FEEDBACK ON;
SET LINESIZE 150;

PROMPT ===================================================
PROMPT CNPS Oracle Demo - Creating User & Schema
PROMPT ===================================================

-- Create demo user (skip if already exists)
DECLARE
    user_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO user_count FROM all_users WHERE username = 'CNPS_DEMO';
    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER cnps_demo IDENTIFIED BY cnps_demo_2026';
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION TO cnps_demo';
        EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO cnps_demo';
        DBMS_OUTPUT.PUT_LINE('Created user cnps_demo/cnps_demo_2026');
    ELSE
        DBMS_OUTPUT.PUT_LINE('User cnps_demo already exists');
    END IF;
END;
/

-- Connect as demo user
ALTER SESSION SET CURRENT_SCHEMA = cnps_demo;

PROMPT ===================================================
PROMPT Dropping existing tables (if any)
PROMPT ===================================================

BEGIN
    FOR t IN (SELECT table_name FROM user_tables) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
    FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('All existing tables and sequences dropped.');
END;
/

PROMPT ===================================================
PROMPT Creating Tables
PROMPT ===================================================

-- 1. REGIONAL OFFICES
CREATE TABLE regional_offices (
    office_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR2(10) NOT NULL UNIQUE,
    name            VARCHAR2(100) NOT NULL,
    region          VARCHAR2(50),
    manager_name    VARCHAR2(100),
    staff_count     NUMBER DEFAULT 0,
    budget_allocated NUMBER(15,2) DEFAULT 0,
    created_at      DATE DEFAULT SYSDATE
);

-- 2. EMPLOYERS
CREATE TABLE employers (
    employer_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_code       VARCHAR2(20) NOT NULL UNIQUE,
    company_name        VARCHAR2(200),
    sector              VARCHAR2(100),
    employee_count      NUMBER,
    regional_code       VARCHAR2(10) REFERENCES regional_offices(code),
    registration_date   DATE,
    status              VARCHAR2(20) DEFAULT 'active',
    last_payment_date   DATE
);

-- 3. CONTRIBUTIONS (main transactional table)
CREATE TABLE contributions (
    contribution_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employer_id         NUMBER NOT NULL REFERENCES employers(employer_id),
    employee_ssn        VARCHAR2(50),
    employee_name       VARCHAR2(200),
    contribution_amount NUMBER(15,2),
    contribution_date   DATE NOT NULL,
    due_date            DATE,
    payment_status      VARCHAR2(20) DEFAULT 'paid',
    regional_code       VARCHAR2(10) REFERENCES regional_offices(code),
    payment_method      VARCHAR2(30),
    late_fee            NUMBER(15,2) DEFAULT 0,
    created_at          DATE DEFAULT SYSDATE
);

-- 4. PENSION PAYMENTS
CREATE TABLE pension_payments (
    payment_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiary_ssn     VARCHAR2(50),
    beneficiary_name    VARCHAR2(200),
    pension_amount      NUMBER(15,2),
    payment_date        DATE NOT NULL,
    payment_status      VARCHAR2(20) DEFAULT 'paid',
    regional_code       VARCHAR2(10) REFERENCES regional_offices(code),
    processing_days     NUMBER DEFAULT 0,
    rejection_reason    VARCHAR2(500),
    created_at          DATE DEFAULT SYSDATE
);

-- 5. WORKPLACE ACCIDENTS (AT/MP Claims)
CREATE TABLE workplace_accidents (
    accident_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_ssn        VARCHAR2(50),
    employee_name       VARCHAR2(200),
    employer_id         NUMBER NOT NULL REFERENCES employers(employer_id),
    accident_date       DATE NOT NULL,
    accident_type       VARCHAR2(50),
    severity            VARCHAR2(20),
    claim_amount        NUMBER(15,2),
    claim_status        VARCHAR2(30) DEFAULT 'pending',
    regional_code       VARCHAR2(10) REFERENCES regional_offices(code),
    processing_days     NUMBER DEFAULT 0,
    rejection_reason    VARCHAR2(500),
    created_at          DATE DEFAULT SYSDATE
);

-- Indexes for performance
CREATE INDEX idx_contrib_region ON contributions(regional_code);
CREATE INDEX idx_contrib_status ON contributions(payment_status);
CREATE INDEX idx_contrib_date ON contributions(contribution_date);
CREATE INDEX idx_contrib_employer ON contributions(employer_id);
CREATE INDEX idx_pension_region ON pension_payments(regional_code);
CREATE INDEX idx_pension_status ON pension_payments(payment_status);
CREATE INDEX idx_accident_region ON workplace_accidents(regional_code);
CREATE INDEX idx_accident_status ON workplace_accidents(claim_status);

PROMPT Tables created successfully.

PROMPT ===================================================
PROMPT Inserting Regional Offices
PROMPT ===================================================

INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('YAO', 'Yaoundé', 'Centre', 'Marie Nguema', 25, 150000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('DLA', 'Douala', 'Littoral', 'Paul Mbarga', 30, 200000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('BAF', 'Bafoussam', 'Ouest', 'Jean Kamga', 18, 120000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('GAR', 'Garoua', 'Nord', 'Ahmadou Bello', 15, 100000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('BMD', 'Bamenda', 'Nord-Ouest', 'Grace Fon', 12, 80000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('BUE', 'Buea', 'Sud-Ouest', 'John Epie', 14, 90000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('BER', 'Bertoua', 'Est', 'Claude Atangana', 10, 70000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('MAR', 'Maroua', 'Extrême-Nord', 'Fatima Moussa', 16, 85000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('EVD', 'Ebolowa', 'Sud', 'Pierre Mvondo', 8, 60000);
INSERT INTO regional_offices (code, name, region, manager_name, staff_count, budget_allocated)
VALUES ('KRI', 'Kribi', 'Sud', 'Anne Biyaga', 6, 50000);
COMMIT;
PROMPT 10 regional offices inserted.

PROMPT ===================================================
PROMPT Inserting 500 Employers (with data quality issues)
PROMPT ===================================================

DECLARE
    TYPE region_arr IS VARRAY(10) OF VARCHAR2(10);
    regions region_arr := region_arr('YAO','DLA','BAF','GAR','BMD','BUE','BER','MAR','EVD','KRI');
    v_reg VARCHAR2(10);
    v_sector VARCHAR2(30);
    v_company VARCHAR2(200);
    v_emp_count NUMBER;
    v_status VARCHAR2(20);
    v_last_pay DATE;
BEGIN
    FOR i IN 1..500 LOOP
        v_reg := regions(TRUNC(DBMS_RANDOM.VALUE(1,11)));
        v_sector := CASE TRUNC(DBMS_RANDOM.VALUE(1,9))
            WHEN 1 THEN 'Manufacturing' WHEN 2 THEN 'Services'
            WHEN 3 THEN 'Agriculture' WHEN 4 THEN 'Mining'
            WHEN 5 THEN 'Construction' WHEN 6 THEN 'Education'
            WHEN 7 THEN 'Healthcare' ELSE 'Banking' END;

        -- 5% missing company names
        IF DBMS_RANDOM.VALUE < 0.05 THEN
            v_company := NULL;
        ELSE
            v_company := v_sector || ' Company ' || TO_CHAR(i);
        END IF;

        -- 3% invalid employee counts
        IF DBMS_RANDOM.VALUE < 0.03 THEN
            v_emp_count := CASE TRUNC(DBMS_RANDOM.VALUE(1,5))
                WHEN 1 THEN -1 WHEN 2 THEN 0 WHEN 3 THEN 99999 ELSE NULL END;
        ELSE
            v_emp_count := TRUNC(DBMS_RANDOM.VALUE(5,501));
        END IF;

        -- 10% delinquent employers
        IF DBMS_RANDOM.VALUE < 0.1 THEN
            v_status := 'delinquent';
            v_last_pay := SYSDATE - TRUNC(DBMS_RANDOM.VALUE(90,366));
        ELSE
            v_status := CASE TRUNC(DBMS_RANDOM.VALUE(1,4))
                WHEN 1 THEN 'active' WHEN 2 THEN 'active'
                WHEN 3 THEN 'suspended' ELSE 'inactive' END;
            v_last_pay := SYSDATE - TRUNC(DBMS_RANDOM.VALUE(1,31));
        END IF;

        INSERT INTO employers (employer_code, company_name, sector, employee_count,
            regional_code, registration_date, status, last_payment_date)
        VALUES ('EMP-' || LPAD(TO_CHAR(i+1000), 4, '0'), v_company, v_sector, v_emp_count,
            v_reg, SYSDATE - TRUNC(DBMS_RANDOM.VALUE(30,1096)), v_status, v_last_pay);
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('500 employers inserted.');
END;
/

PROMPT ===================================================
PROMPT Inserting ~15,000 Contributions (with anomalies)
PROMPT ===================================================

DECLARE
    v_contrib_date DATE;
    v_due_date DATE;
    v_amount NUMBER(15,2);
    v_status VARCHAR2(20);
    v_method VARCHAR2(30);
    v_ssn VARCHAR2(50);
    v_name VARCHAR2(200);
    v_late_fee NUMBER(15,2);
    v_emp_id NUMBER;
    v_reg VARCHAR2(10);
    v_emp_count NUMBER;
    CURSOR emp_cursor IS SELECT employer_id, regional_code, employee_count FROM employers WHERE employee_count > 0;
BEGIN
    FOR emp_rec IN emp_cursor LOOP
        v_emp_id := emp_rec.employer_id;
        v_reg := emp_rec.regional_code;
        v_emp_count := emp_rec.employee_count;
        IF v_emp_count IS NULL OR v_emp_count <= 0 THEN
            v_emp_count := 10;
        END IF;

        FOR month_offset IN 0..11 LOOP
            FOR c IN 1..TRUNC(DBMS_RANDOM.VALUE(1, LEAST(v_emp_count, 50) + 1)) LOOP
                v_contrib_date := ADD_MONTHS(SYSDATE, -month_offset) - TRUNC(DBMS_RANDOM.VALUE(0,29));
                v_due_date := v_contrib_date + 30;

                -- 15% payment issues
                IF DBMS_RANDOM.VALUE < 0.15 THEN
                    v_status := CASE TRUNC(DBMS_RANDOM.VALUE(1,4))
                        WHEN 1 THEN 'overdue' WHEN 2 THEN 'rejected' ELSE 'partial' END;
                    IF v_status = 'overdue' THEN
                        v_late_fee := GREATEST(0, (SYSDATE - v_due_date) * 500);
                    ELSE
                        v_late_fee := 0;
                    END IF;
                ELSE
                    v_status := 'paid';
                    v_late_fee := 0;
                END IF;

                -- Amount anomalies
                IF DBMS_RANDOM.VALUE < 0.05 THEN
                    v_amount := CASE TRUNC(DBMS_RANDOM.VALUE(1,5))
                        WHEN 1 THEN 0 WHEN 2 THEN -1000 WHEN 3 THEN 999999 ELSE NULL END;
                ELSIF v_reg = 'YAO' AND DBMS_RANDOM.VALUE < 0.3 THEN
                    v_amount := ROUND(DBMS_RANDOM.VALUE(25000,45000), 2);
                ELSIF v_reg IN ('KRI','EVD') AND DBMS_RANDOM.VALUE < 0.4 THEN
                    v_amount := ROUND(DBMS_RANDOM.VALUE(5000,15000), 2);
                ELSE
                    v_amount := ROUND(DBMS_RANDOM.VALUE(15000,25000), 2);
                END IF;

                -- 2% missing SSN
                IF DBMS_RANDOM.VALUE < 0.02 THEN
                    v_ssn := NULL;
                    v_name := 'Unknown Employee ' || TO_CHAR(c);
                ELSE
                    v_ssn := 'SSN' || TO_CHAR(v_emp_id) || LPAD(TO_CHAR(c), 3, '0');
                    v_name := 'Employee ' || TO_CHAR(c) || ' - Emp ' || TO_CHAR(v_emp_id);
                END IF;

                v_method := CASE TRUNC(DBMS_RANDOM.VALUE(1,5))
                    WHEN 1 THEN 'bank_transfer' WHEN 2 THEN 'cash'
                    WHEN 3 THEN 'check' WHEN 4 THEN 'mobile_money' ELSE 'bank_transfer' END;

                INSERT INTO contributions (employer_id, employee_ssn, employee_name,
                    contribution_amount, contribution_date, due_date, payment_status,
                    regional_code, payment_method, late_fee)
                VALUES (v_emp_id, v_ssn, v_name, v_amount, v_contrib_date, v_due_date,
                    v_status, v_reg, v_method, v_late_fee);
            END LOOP;
        END LOOP;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Contributions inserted.');
END;
/

PROMPT ===================================================
PROMPT Inserting 2,000 Pension Payments (with delays/rejections)
PROMPT ===================================================

DECLARE
    v_amount NUMBER(15,2);
    v_status VARCHAR2(20);
    v_days NUMBER;
    v_reg VARCHAR2(10);
    v_reason VARCHAR2(500);
    TYPE region_arr IS VARRAY(10) OF VARCHAR2(10);
    regions region_arr := region_arr('YAO','DLA','BAF','GAR','BMD','BUE','BER','MAR','EVD','KRI');
BEGIN
    FOR i IN 1..2000 LOOP
        v_reg := regions(TRUNC(DBMS_RANDOM.VALUE(1,11)));

        -- 20% processing delays, 15% rejected
        IF DBMS_RANDOM.VALUE < 0.2 THEN
            v_days := TRUNC(DBMS_RANDOM.VALUE(45,121));
            v_status := 'pending';
        ELSIF DBMS_RANDOM.VALUE < 0.35 THEN
            v_days := TRUNC(DBMS_RANDOM.VALUE(5,31));
            v_status := 'rejected';
        ELSE
            v_days := TRUNC(DBMS_RANDOM.VALUE(1,22));
            v_status := 'paid';
        END IF;

        -- Amount anomalies
        IF v_status = 'rejected' THEN
            v_amount := 0;
            v_reason := CASE TRUNC(DBMS_RANDOM.VALUE(1,6))
                WHEN 1 THEN 'Incomplete documentation'
                WHEN 2 THEN 'Age verification failed'
                WHEN 3 THEN 'Contribution period insufficient'
                WHEN 4 THEN 'Duplicate claim'
                WHEN 5 THEN 'System error' ELSE 'Eligibility criteria not met' END;
        ELSIF DBMS_RANDOM.VALUE < 0.05 THEN
            v_amount := CASE TRUNC(DBMS_RANDOM.VALUE(1,4))
                WHEN 1 THEN 999999 WHEN 2 THEN -5000 ELSE NULL END;
            v_reason := NULL;
        ELSIF v_reg IN ('YAO','DLA') THEN
            v_amount := ROUND(DBMS_RANDOM.VALUE(80000,150000), 2);
            v_reason := NULL;
        ELSE
            v_amount := ROUND(DBMS_RANDOM.VALUE(45000,85000), 2);
            v_reason := NULL;
        END IF;

        INSERT INTO pension_payments (beneficiary_ssn, beneficiary_name, pension_amount,
            payment_date, payment_status, regional_code, processing_days, rejection_reason)
        VALUES ('SSN' || TO_CHAR(i+10000), 'Pensioner ' || TO_CHAR(i),
            v_amount, SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,366)),
            v_status, v_reg, v_days, v_reason);
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('2,000 pension payments inserted.');
END;
/

PROMPT ===================================================
PROMPT Inserting 800 Workplace Accidents (with regional bias)
PROMPT ===================================================

DECLARE
    v_amount NUMBER(15,2);
    v_status VARCHAR2(30);
    v_severity VARCHAR2(20);
    v_days NUMBER;
    v_reg VARCHAR2(10);
    v_type VARCHAR2(30);
    v_ssn VARCHAR2(50);
    v_name VARCHAR2(200);
    v_reason VARCHAR2(500);
    v_emp_id NUMBER;
    TYPE region_arr IS VARRAY(10) OF VARCHAR2(10);
    regions region_arr := region_arr('YAO','DLA','BAF','GAR','BMD','BUE','BER','MAR','EVD','KRI');
    TYPE types_arr IS VARRAY(8) OF VARCHAR2(30);
    types types_arr := types_arr('Fall','Cut','Burn','Machinery','Chemical','Vehicle','Lifting','Other');
BEGIN
    FOR i IN 1..800 LOOP
        v_reg := regions(TRUNC(DBMS_RANDOM.VALUE(1,11)));
        v_type := types(TRUNC(DBMS_RANDOM.VALUE(1,9)));
        v_severity := CASE TRUNC(DBMS_RANDOM.VALUE(1,5))
            WHEN 1 THEN 'Minor' WHEN 2 THEN 'Moderate' WHEN 3 THEN 'Severe' ELSE 'Fatal' END;
        v_emp_id := TRUNC(DBMS_RANDOM.VALUE(1,501));

        -- Regional bias: smaller offices reject more
        IF v_reg IN ('KRI','EVD','BER') AND DBMS_RANDOM.VALUE < 0.4 THEN
            v_status := 'rejected';
            v_amount := 0;
            v_days := TRUNC(DBMS_RANDOM.VALUE(30,91));
            v_reason := CASE TRUNC(DBMS_RANDOM.VALUE(1,6))
                WHEN 1 THEN 'Insufficient evidence' WHEN 2 THEN 'Not work-related'
                WHEN 3 THEN 'Late reporting' WHEN 4 THEN 'Pre-existing condition'
                WHEN 5 THEN 'Fraudulent claim' ELSE 'Documentation incomplete' END;
        ELSE
            IF v_severity = 'Fatal' THEN
                v_amount := ROUND(DBMS_RANDOM.VALUE(2000000,5000000), 2);
                v_days := TRUNC(DBMS_RANDOM.VALUE(60,181));
                v_status := 'under_investigation';
            ELSIF v_severity = 'Severe' THEN
                v_amount := ROUND(DBMS_RANDOM.VALUE(500000,2000000), 2);
                v_days := TRUNC(DBMS_RANDOM.VALUE(30,91));
                v_status := CASE TRUNC(DBMS_RANDOM.VALUE(1,3))
                    WHEN 1 THEN 'approved' WHEN 2 THEN 'pending' ELSE 'under_investigation' END;
            ELSE
                v_amount := ROUND(DBMS_RANDOM.VALUE(50000,500000), 2);
                v_days := TRUNC(DBMS_RANDOM.VALUE(5,46));
                v_status := CASE TRUNC(DBMS_RANDOM.VALUE(1,3))
                    WHEN 1 THEN 'approved' WHEN 2 THEN 'approved' ELSE 'pending' END;
            END IF;
            v_reason := NULL;
        END IF;

        -- 3% missing employee data
        IF DBMS_RANDOM.VALUE < 0.03 THEN
            v_ssn := NULL;
            v_name := 'Unknown Employee';
        ELSE
            v_ssn := 'SSN' || TO_CHAR(i+20000);
            v_name := 'Accident Victim ' || TO_CHAR(i);
        END IF;

        INSERT INTO workplace_accidents (employee_ssn, employee_name, employer_id,
            accident_date, accident_type, severity, claim_amount, claim_status,
            regional_code, processing_days, rejection_reason)
        VALUES (v_ssn, v_name, v_emp_id,
            SYSDATE - TRUNC(DBMS_RANDOM.VALUE(0,731)),
            v_type, v_severity, v_amount, v_status,
            v_reg, v_days, v_reason);
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('800 workplace accidents inserted.');
END;
/

PROMPT ===================================================
PROMPT Gathering Statistics
PROMPT ===================================================

BEGIN
    DBMS_STATS.GATHER_TABLE_STATS('CNPS_DEMO', 'REGIONAL_OFFICES');
    DBMS_STATS.GATHER_TABLE_STATS('CNPS_DEMO', 'EMPLOYERS');
    DBMS_STATS.GATHER_TABLE_STATS('CNPS_DEMO', 'CONTRIBUTIONS');
    DBMS_STATS.GATHER_TABLE_STATS('CNPS_DEMO', 'PENSION_PAYMENTS');
    DBMS_STATS.GATHER_TABLE_STATS('CNPS_DEMO', 'WORKPLACE_ACCIDENTS');
    DBMS_OUTPUT.PUT_LINE('Statistics gathered');
END;
/

PROMPT ===================================================
PROMPT Data Summary
PROMPT ===================================================

SELECT 'regional_offices' AS table_name, COUNT(*) AS row_count FROM regional_offices
UNION ALL
SELECT 'employers', COUNT(*) FROM employers
UNION ALL
SELECT 'contributions', COUNT(*) FROM contributions
UNION ALL
SELECT 'pension_payments', COUNT(*) FROM pension_payments
UNION ALL
SELECT 'workplace_accidents', COUNT(*) FROM workplace_accidents
ORDER BY table_name;

PROMPT ===================================================
PROMPT Data Quality Issues Summary (Anomalies)
PROMPT ===================================================

SELECT 'Invalid contribution amounts' AS issue,
       COUNT(*) AS count FROM contributions WHERE contribution_amount <= 0 OR contribution_amount IS NULL
UNION ALL
SELECT 'Overdue payments', COUNT(*) FROM contributions WHERE payment_status = 'overdue'
UNION ALL
SELECT 'Missing employee SSNs', COUNT(*) FROM contributions WHERE employee_ssn IS NULL
UNION ALL
SELECT 'Rejected pension claims', COUNT(*) FROM pension_payments WHERE payment_status = 'rejected'
UNION ALL
SELECT 'Rejected accident claims', COUNT(*) FROM workplace_accidents WHERE claim_status = 'rejected'
UNION ALL
SELECT 'Delinquent employers', COUNT(*) FROM employers WHERE status = 'delinquent'
UNION ALL
SELECT 'Employers with missing names', COUNT(*) FROM employers WHERE company_name IS NULL;

PROMPT ===================================================
PROMPT Regional Claim Rejection Rates (shows bias)
PROMPT ===================================================

SELECT regional_code, COUNT(*) AS total,
       SUM(CASE WHEN claim_status = 'rejected' THEN 1 ELSE 0 END) AS rejected,
       ROUND(100 * SUM(CASE WHEN claim_status = 'rejected' THEN 1 ELSE 0 END) / COUNT(*), 1) AS reject_pct
FROM workplace_accidents GROUP BY regional_code ORDER BY reject_pct DESC;

PROMPT ===================================================
PROMPT ✅ CNPS Oracle Demo Database Setup Complete!
PROMPT ===================================================
PROMPT Connection string for SAAS Settings:
PROMPT   oracle+oracledb://cnps_demo:cnps_demo_2026@localhost:1521/XEPDB1
PROMPT
PROMPT Or if using a different host:
PROMPT   oracle+oracledb://cnps_demo:cnps_demo_2026@YOUR_HOST:1521/YOUR_SERVICE
PROMPT
PROMPT ===================================================